# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to Cloud Run when a release is created

name: Build and Deploy to Cloud Run

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}
  IMAGE: gateway
  REGISTRY_HOSTNAME: us.gcr.io
  REVERSE_PROXY_TARGET: ${{ secrets.REVERSE_PROXY_TARGET }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          docker build -t "$REGISTRY_HOSTNAME/$GOOGLE_PROJECT/$IMAGE:$GITHUB_SHA" \
            -t "$REGISTRY_HOSTNAME/$GOOGLE_PROJECT/$IMAGE:$GITHUB_RELEASE_TAG" \
            -t "$REGISTRY_HOSTNAME/$GOOGLE_PROJECT/$IMAGE:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg REVERSE_PROXY_TARGET="$REVERSE_PROXY_TARGET" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push --all-tags $REGISTRY_HOSTNAME/$GOOGLE_PROJECT/$IMAGE

      # Deploy the Docker image to the Cloud Run service
      - name: Deploy API
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE --image $REGISTRY_HOSTNAME/$GOOGLE_PROJECT/$IMAGE:${GITHUB_SHA} --platform managed --project $GOOGLE_PROJECT --region us-central1 --allow-unauthenticated
